export const RESTAURANTES = [
  {
    id: '1',
    nome: 'Burger Supreme',
    categoria: 'Hambúrgueres',
    avaliacao: 4.8,
    tempo: '25–35 min',
    entrega: 'Grátis',
    cor: '#E8452C',
    emoji: '🍔',
    lat: -22.4012,
    lng: -43.6589,
    produtos: [
      { id: 'p1', nome: 'Classic Smash',    descricao: 'Blend 180g, queijo cheddar, alface, tomate fresco',      preco: 32.90, emoji: '🍔' },
      { id: 'p2', nome: 'BBQ Bacon',        descricao: 'Blend 180g, bacon crocante, molho BBQ defumado',         preco: 37.90, emoji: '🥓' },
      { id: 'p3', nome: 'Veggie Deluxe',    descricao: 'Hambúrguer de grão-de-bico, rúcula, tomate seco',        preco: 34.90, emoji: '🥗' },
      { id: 'p4', nome: 'Batata Frita Grande', descricao: 'Crocante por fora, macia por dentro, sal rosa',       preco: 16.90, emoji: '🍟' },
    ],
  },
  {
    id: '2',
    nome: 'Pizza Napoli',
    categoria: 'Pizzas',
    avaliacao: 4.9,
    tempo: '40–50 min',
    entrega: 'R$ 5,00',
    cor: '#D97706',
    emoji: '🍕',
    lat: -22.4058,
    lng: -43.6650,
    produtos: [
      { id: 'p5', nome: 'Margherita',     descricao: 'Molho de tomate, mozzarella fior di latte, manjericão',    preco: 52.90, emoji: '🍕' },
      { id: 'p6', nome: 'Pepperoni',      descricao: 'Molho de tomate, mozzarella, pepperoni italiano',          preco: 58.90, emoji: '🌶️' },
      { id: 'p7', nome: 'Quatro Queijos', descricao: 'Mozzarella, gorgonzola, parmesão, provolone',              preco: 61.90, emoji: '🧀' },
      { id: 'p8', nome: 'Frango com Catupiry', descricao: 'Frango desfiado, catupiry cremoso, oregano',          preco: 56.90, emoji: '🍗' },
    ],
  },
  {
    id: '3',
    nome: 'Sushi Zen',
    categoria: 'Japonês',
    avaliacao: 4.7,
    tempo: '35–45 min',
    entrega: 'R$ 8,00',
    cor: '#0891B2',
    emoji: '🍣',
    lat: -22.3995,
    lng: -43.6672,
    produtos: [
      { id: 'p9',  nome: 'Combo Salmão 20 peças', descricao: 'Niguiri, uramaki e temaki de salmão fresco',       preco: 68.90, emoji: '🍣' },
      { id: 'p10', nome: 'Temaki de Atum',         descricao: 'Atum fresco, cream cheese, cebolinha',            preco: 28.90, emoji: '🌯' },
      { id: 'p11', nome: 'Missoshiru',             descricao: 'Caldo de missô com tofu e alga wakame',           preco: 12.90, emoji: '🍲' },
      { id: 'p12', nome: 'Gyoza Frito 8 un.',      descricao: 'Pastel japonês recheado com carne e gengibre',    preco: 26.90, emoji: '🥟' },
    ],
  },
  {
    id: '4',
    nome: 'Tacos El Rey',
    categoria: 'Mexicano',
    avaliacao: 4.5,
    tempo: '30–40 min',
    entrega: 'R$ 6,00',
    cor: '#16A34A',
    emoji: '🌮',
    lat: -22.4044,
    lng: -43.6598,
    produtos: [
      { id: 'p13', nome: 'Taco Carnitas',       descricao: 'Carne de porco desfiada, pico de gallo, coentro',   preco: 19.90, emoji: '🌮' },
      { id: 'p14', nome: 'Burrito Supremo',     descricao: 'Arroz, feijão, carne bovina, queijo, creme',        preco: 34.90, emoji: '🌯' },
      { id: 'p15', nome: 'Nachos Guacamole',    descricao: 'Chips de milho, guacamole fresco, jalapeños',       preco: 28.90, emoji: '🥑' },
      { id: 'p16', nome: 'Quesadilla de Frango',descricao: 'Tortilla grelhada, queijo derretido, frango',       preco: 26.90, emoji: '🫓' },
    ],
  },
  {
    id: '5',
    nome: 'Green Bowl',
    categoria: 'Saudável',
    avaliacao: 4.6,
    tempo: '20–30 min',
    entrega: 'Grátis',
    cor: '#059669',
    emoji: '🥗',
    lat: -22.3988,
    lng: -43.6625,
    produtos: [
      { id: 'p17', nome: 'Buddha Bowl',          descricao: 'Quinoa, grão-de-bico, abacate, cenoura, tahine',   preco: 38.90, emoji: '🥗' },
      { id: 'p18', nome: 'Wrap de Frango',        descricao: 'Peito grelhado, alface, tomate, molho iogurte',   preco: 29.90, emoji: '🌯' },
      { id: 'p19', nome: 'Smoothie Verde',        descricao: 'Espinafre, banana, maçã verde, gengibre',         preco: 18.90, emoji: '🥤' },
      { id: 'p20', nome: 'Açaí Bowl Fit',         descricao: 'Açaí puro, granola sem açúcar, frutas frescas',   preco: 28.90, emoji: '🫐' },
    ],
  },
  {
    id: '6',
    nome: 'Cantina da Nonna',
    categoria: 'Massas',
    avaliacao: 4.9,
    tempo: '45–55 min',
    entrega: 'R$ 7,00',
    cor: '#7C3AED',
    emoji: '🍝',
    lat: -22.4071,
    lng: -43.6580,
    produtos: [
      { id: 'p21', nome: 'Fettuccine al Funghi', descricao: 'Massa fresca, porcini, creme de leite, parmesão',  preco: 52.90, emoji: '🍝' },
      { id: 'p22', nome: 'Lasanha Bolonhesa',    descricao: 'Massa fresca, ragú de carne, béchamel gratinada',  preco: 48.90, emoji: '🫕' },
      { id: 'p23', nome: 'Bruschetta Classica',  descricao: 'Pão artesanal, tomate fresco, azeite, manjericão', preco: 19.90, emoji: '🍞' },
      { id: 'p24', nome: 'Tiramisu',             descricao: 'Ladyfinger, mascarpone, espresso, cacau em pó',    preco: 22.90, emoji: '🍮' },
    ],
  },
  {
    id: '7',
    nome: 'Churrascaria Gaúcha',
    categoria: 'Churrasco',
    avaliacao: 4.7,
    tempo: '50–65 min',
    entrega: 'R$ 10,00',
    cor: '#B45309',
    emoji: '🥩',
    lat: -22.4085,
    lng: -43.6635,
    produtos: [
      { id: 'p25', nome: 'Picanha 300g',          descricao: 'Picanha premium na brasa, farofa e vinagrete',    preco: 79.90, emoji: '🥩' },
      { id: 'p26', nome: 'Costela no Bafo 500g',  descricao: 'Costela bovina 8h de preparo, mandioca cozida',  preco: 89.90, emoji: '🍖' },
      { id: 'p27', nome: 'Linguiça Artesanal',    descricao: 'Linguiça de pernil defumada, mostarda e pão',    preco: 32.90, emoji: '🌭' },
      { id: 'p28', nome: 'Fraldinha Grelhada',    descricao: 'Corte nobre grelhado, arroz, farofa e salada',   preco: 64.90, emoji: '🥩' },
    ],
  },
  {
    id: '8',
    nome: 'Açaí da Vila',
    categoria: 'Açaí',
    avaliacao: 4.8,
    tempo: '15–25 min',
    entrega: 'Grátis',
    cor: '#9333EA',
    emoji: '🫐',
    lat: -22.4002,
    lng: -43.6660,
    produtos: [
      { id: 'p29', nome: 'Açaí 500ml',          descricao: 'Açaí puro batido, granola, banana, mel',           preco: 24.90, emoji: '🫐' },
      { id: 'p30', nome: 'Açaí Especial 1L',    descricao: 'Açaí, morango, kiwi, granola, leite condensado',   preco: 42.90, emoji: '🍓' },
      { id: 'p31', nome: 'Vitamina de Açaí',    descricao: 'Açaí com leite, banana e aveia',                   preco: 19.90, emoji: '🥤' },
      { id: 'p32', nome: 'Tigela com Cobertura', descricao: 'Açaí, paçoca, Nutella, granola e morango',        preco: 34.90, emoji: '🍫' },
    ],
  },
];

export function formatarPreco(valor) {
  return `R$ ${valor.toFixed(2).replace('.', ',')}`;
}
